version: '3.8'

services:
  statistics-service:
    build: ./statistics-service/service
    image: service
    container_name: "statistics-service"
    ports:
      - "9090:9090"
    depends_on:
      - statistics-db
    environment:
      - DB_HOST=stats-db
      - DB_PORT=5432
      - DB_NAME=explore
      - SPRING_DATASOURCE_USERNAME=explore
      - SPRING_DATASOURCE_PASSWORD=explore

  statistics-db:
    image: postgres:14-alpine
    container_name: "statistics-db"
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=explore
      - POSTGRES_USER=explore
      - POSTGRES_PASSWORD=explore